Rudy/testing
team-skechers/Lunchin pull request #32
Opened 2019-05-22 20:57 UTC by Rodolfoguzman25

Changed 'joesFrontEndCookieParser' to cookieParser.
NPM installed jest, sinon, enzyme, and supertest.
Created automated test for get request to yelp API, and cookieParser.

2019-05-22 23:03 UTC, conor-jh requested changes
Hey Rudy, these look good! Check out my inline comments in some of your test files… just a few things to clarify before we merge in 👍

2019-05-22 23:03 UTC, conor-jh commented on testing/authenticate.test.js
> +    expect(authenticate.cookieParser('bobby= henry; sally=harry; christian= freddy;'))
@Rodolfoguzman25 Can you add `describe` and/or `it` calls here to clarify what’s being tested? With the hard-coded data, it’s a little unclear… 🙏

2019-05-22 23:03 UTC, conor-jh commented on testing/server.test.js
> +      it('responds with 200 status and text/html content type', () => {
Change `it` to expect `application/json` content type to reflect the actual test

2019-05-22 23:03 UTC, conorsexton commented on testing/server.test.js
> +      it('responds with an empty json object if name/zip are undefined', () => {
Update this test description to match the test (responds with 404… not clear what the response body is from the test itself).

Should also probably test expect assertion for missing name **and** missing zip

2019-05-22 23:03 UTC, conorsexton commented on testing/server.test.js
> +      });
Doesn’t have to be part of this pull request, but it’d probably be good to add tests to check the proper data points are coming back… e.g. 
```js
.expect(data[0].name).toBe('Chipotle')
```

2019-05-23 14:32 UTC, conor-jh approved these changes
Thanks for those changes, looks good 🃏

2019-05-23 14:36 UTC, Donaldblanc approved these changes
nice work on the testing using Regex is a clever way to ensure the correct data is received

2019-05-23 14:36 UTC, Donaldblanc commented
Awesome Job man, keep up the good work.

2019-05-23 14:36 UTC, merged